---
name: Build

on:
  push: {}

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - run: corepack enable

      - name: Install Dependencies
        run: yarn

      - name: Run CI
        run: yarn ci
